# Generated by Django 4.1.6 on 2024-03-17 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_upload', '0003_listing_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='thumbnail',
            field=models.CharField(max_length=255),
        ),
    ]
