# Generated by Django 4.1.6 on 2024-03-26 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_upload', '0004_alter_listing_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.CharField(default='testing', max_length=2000),
            preserve_default=False,
        ),
    ]
