# Generated by Django 5.0.2 on 2024-04-08 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_upload', '0005_listing_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='listing',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
