# Generated by Django 5.0.2 on 2024-03-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recommendation_algorithm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(default='UNKNOWN_ISBN', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookinteraction',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookinteraction',
            name='interaction_type',
            field=models.CharField(choices=[('VIEW', 'View'), ('ADD', 'Add to Library'), ('RATE', 'Rating')], max_length=20),
        ),
        migrations.AlterField(
            model_name='bookinteraction',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
